### ISSUE TITLE
Update links to other webapps

### ISSUE THREAD

**Issue by esune** [bcgov/dts-esr-demo#20]
Links pointing to OCP3 deployments of services will need to be updated once the `prod` instances are migrated to OCP4.

[Here](https://github.com/bcgov/essential-services-delivery/issues/99) is a list of URLs that need changing.

[This issue](https://github.com/bcgov/essential-services-delivery/issues/99) tracks the changes to the deployments.

**Comment by wadeking98** [comment]
links working in prod
