### ISSUE TITLE
Demo deployment decommissioning

### ISSUE THREAD

**Issue by esune** [bcgov/dts-esr-demo#56]
In order to decommission the demo, we need to complete the following steps:
- [x] remove references from public-facing the [BC Digital Trust website](https://digital.gov.bc.ca/digital-trust/) (@alexgmetcalf )
- [x] spin down the deployments (@WadeBarnes / @esune )
- [x] remove configurations from OCP (@WadeBarnes / @esune / @rajpalc7 )
- [x] close this issue (@WadeBarnes / @esune )
- [x] archive this repository (@WadeBarnes / @esune )

**Comment by alexgmetcalf** [comment]
Confirmed: no references on website

**Comment by esune** [comment]
@WadeBarnes @rajpalc7 wallets have been backed-up and deployments spun down in all environments. Everything is ready for resources to be freed.
